#!/usr/bin/env python
#
#
import requests
import xml.etree.ElementTree as ET

fritzbox_ip='10.0.0.1'

def printDataRate(ip):
  url = "http://%s:49000/igdupnp/control/WANCommonIFC1" % ip
  body = "<?xml version='1.0' encoding='utf-8'?> <s:Envelope s:encodingStyle='http://schemas.xmlsoap.org/soap/encoding/' xmlns:s='http://schemas.xmlsoap.org/soap/envelope/'> <s:Body> <u:GetAddonInfos xmlns:u='urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1' /> </s:Body> </s:Envelope>"
  headers = { 
    "Content-Type": "text/xml; charset=\"utf-8\"",
    "SoapAction"  : "urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1#GetAddonInfos",
  }

  response = requests.post(url, data=body, headers=headers)
  if response.status_code == 200:
    responseXML = response.text
    myroot = ET.fromstring(responseXML)
    element = myroot[0].find('{urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1}GetAddonInfosResponse')
    print("ByteSendRate.value %s"       % element.find('NewByteSendRate').text)
    print("ByteReceiveRate.value %s"    % element.find('NewByteReceiveRate').text)
    print("TotalBytesSent.value %s"     % element.find('NewTotalBytesSent').text)
    print("TotalBytesReceived.value %s" % element.find('NewTotalBytesReceived').text)
  else:
    print('ERROR %d',response.status_code)

def printBandwith(ip):
  url = "http://%s:49000/igdupnp/control/WANCommonIFC1" % ip
  body = "<?xml version='1.0' encoding='utf-8'?> <s:Envelope s:encodingStyle='http://schemas.xmlsoap.org/soap/encoding/' xmlns:s='http://schemas.xmlsoap.org/soap/envelope/'> <s:Body> <u:GetCommonLinkProperties xmlns:u='urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1' /> </s:Body> </s:Envelope>"
  headers = { 
    "Content-Type": "text/xml; charset=\"utf-8\"",
    "SoapAction"  : "urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1#GetCommonLinkProperties",
  }

  response = requests.post(url, data=body, headers=headers)
  if response.status_code == 200:
    responseXML = response.text
    myroot = ET.fromstring(responseXML)
    element = myroot[0].find('{urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1}GetCommonLinkPropertiesResponse')
    print("UpstreamMaxBitRate.value %s"   % element.find('NewLayer1UpstreamMaxBitRate').text)
    print("DownstreamMaxBitRate.value %s" % element.find('NewLayer1DownstreamMaxBitRate').text)
  else:
    print('ERROR %d',response.status_code)


printDataRate(fritzbox_ip)
printBandwith(fritzbox_ip)