#!/bin/sh
# -*- sh -*-
# 
# Shows number of user sessions in the system.
# Distinct per user (users can have multiple devices
# with sessions, these are combined as 1 session)
#
# Non-expired sessions are sessions which have an
# expiry timestamp in the future
#
# Active sessions are sessions with activity in the
# last 15 minutes.
# 

if [ "$1" = "config" ]; then
  echo "graph_title Mattermost sessions"
  echo "graph_args --lower-limit 0 --base 1000" 
  echo "graph_vlabel number of sessions"
  echo "graph_category mattermost"
  echo "graph_info Number of sessions"
  echo "graph_total Total"

  echo "active_hour.label Active last hour"
  echo "active_hour.type GAUGE"
  echo "active_hour.draw AREA"

  echo "active_day.label Active last day"
  echo "active_day.type GAUGE"
  echo "active_day.draw STACK"

  echo "active_week.label Active last week"
  echo "active_week.type GAUGE"
  echo "active_week.draw STACK"

  echo "valid.label Not expired"
  echo "valid.type GAUGE"
  echo "valid.draw STACK"
 
  exit 0
fi

# Selects the session with the most recent activity per user.
# If a user was active within the last hour, the sessions is
# counted as "active". If the session is still valid but has
# no recent activity, the session is counted as "valid".

# Periods in seconds
hour=3600
day=86400
week=604800
recentlyactiveperiod=604800000

# Measurements:
sudo -u mattermost psql --no-align --field-separator=" " --quiet <<EOF \
        | grep -v label \
        | grep -v rows 
  select label, count(userid) -1 as "value"
  from (
	-- The dummy values make sure at least one of each value is present.
	      select 'dummy' as userid , 'active_hour.value' as label
	union select 'dummy' as userid , 'active_day.value' as label
	union select 'dummy' as userid , 'active_week.value' as label
	union select 'dummy' as userid,  'valid.value' as label
	union
	select userid,
		   case when lastactivityat > round(extract (epoch from now()) * 1000 - ${hour} * 1000) then 'active_hour.value'
		        when lastactivityat > round(extract (epoch from now()) * 1000 - ${day}  * 1000) then 'active_day.value'
		        when lastactivityat > round(extract (epoch from now()) * 1000 - ${week} * 1000) then 'active_week.value'
		   else 'valid.value'
		   end as label
	from (
	  select sessions.userid     as userid,
		  max(lastactivityat) as lastactivityat
	  from sessions
	  where expiresat > round(extract (epoch from now()) * 1000)
	  group by sessions.userid ) as activity
	  ) as values
   group by values.label;
EOF
