#!/bin/bash
#
# Faster, leaner, more readable implementation of
# https://wiki.mikrotik.com/wiki/Munin_Monitoring#mikrotikcpu
#
# If you have improved this script, or have more interesting munin plugins, based
# on this script, please consider sending your changes as a pull request.
#
# https://github.com/realrolfje/munin-plugins
#

# Host is determined based on whatever is behind the _ in the filename
# So mikrotikcpu_myawesomehost -> hostname = myawesomehost
myfilename=$0
host="${myfilename##*_}"

# We assume you didn't change the community in the mikrotik configuration.
snmpcommunity="public"

if [ "$1" = 'config' ]
then
  echo "graph_args -l 0 -r --vertical-label percent --lower-limit 0 --upper-limit 100"
  echo "graph_title ${host} CPU usage"
  echo "graph_category system"
  echo "graph_info This graph shows the router's CPU usage."
  echo "graph_order Total"
  echo "graph_vlabel %"
  echo "graph_scale no"
  echo "Total.label CPU Usage"
  echo "Total.draw AREA"
  echo "Total.warning 60"
  echo "Total.critical 90"
  exit 0
fi

cpuload=$(snmpget -v 1 -c ${snmpcommunity} ${host} "HOST-RESOURCES-MIB::hrProcessorLoad.1" | awk '{ print $NF }')
echo "Total.value ${cpuload}"
