#!/usr/bin/python
#
# Reads the last Squelch state and value from the
# logfile of a remotetrx.
#
# See http://www.svxlink.org/doc/man/man1/remotetrx.1.html
#
import sys
import os

logfile = '/dev/shm/remotetrx'

def tail( f, lines=50 ):
    total_lines_wanted = lines

    BLOCK_SIZE = 1024
    f.seek(0, 2)
    block_end_byte = f.tell()
    lines_to_go = total_lines_wanted
    block_number = -1
    blocks = [] # blocks of size BLOCK_SIZE, in reverse order starting
                # from the end of the file
    while lines_to_go > 0 and block_end_byte > 0:
        if (block_end_byte - BLOCK_SIZE > 0):
            # read the last block we haven't yet read
            f.seek(block_number*BLOCK_SIZE, 2)
            blocks.append(f.read(BLOCK_SIZE))
        else:
            # file too small, start from begining
            f.seek(0,0)
            # only read what was not read
            blocks.append(f.read(block_end_byte))
        lines_found = blocks[-1].count('\n')
        lines_to_go -= lines_found
        block_end_byte -= BLOCK_SIZE
        block_number -= 1
    all_read_text = ''.join(reversed(blocks))
    return '\n'.join(all_read_text.splitlines()[-total_lines_wanted:])

if len(sys.argv) > 1 and (str(sys.argv[1])) == 'config':
    print 'graph_title SVXLink Remote RX'
    print 'graph_args --lower-limit 0 --base 1000'
    print 'graph_vlabel Level'
    print 'graph_category sensors'
    print 'graph_info Squelch state and level at trigger time'
    print 'graph_period minute'
    print 'state.label Squelch OPEN'
    print 'state.type GAUGE'
    print 'state.draw AREA'
    print 'state.colour COLOUR16'
    print 'level.label Squelch level'
    print 'level.type GAUGE'
    print 'level.draw LINE' 
    print 'level.colour COLOUR7'

f = open(logfile, 'r')
lines = tail(f)
sqlindex = lines.rfind('The squelch is ')
if sqlindex > 0:
    bracketopen = lines.find(' (',sqlindex)
    bracketclose = lines.find(')',bracketopen)
    print 'state.value ' + lines[sqlindex+15:bracketopen]
    print 'level.value ' + lines[bracketopen+2:bracketclose]
