#!/usr/bin/python2.7
#
# Reads current electricity usage, in Watts,
# from AM550 Smart Energy meter at ttyAMA0
#
import sys
import serial
import datetime

logfile = '/tmp/smartmeter_current.log'

def logdata(fields):
    current_datetime = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    strfields=[str(item) for item in fields]
    line = current_datetime + ';' + (';'.join(strfields)) + '\n'
    try:
        with open(logfile, 'a') as file:
            file.write(line)
    except Exception as e:
        sys.stderr.write("An error occurred: %s\n" % e)


def readserial():
    try:
        with serial.Serial(
            port='/dev/ttyAMA0',
            baudrate = 115200,
            parity=serial.PARITY_NONE,
            stopbits=serial.STOPBITS_ONE,
            bytesize=serial.EIGHTBITS,
            timeout=1
        ) as ser:
            readings={}
            while len(readings) < 3:
                x = ser.readline()
                if x[0:7] == "1-0:1.7":
                    readings["huidig"] = float(x[10:16])*1000
                if x[0:9] == "1-0:1.8.1":
                    readings["T1"] = float(x[10:19])*1000
                if x[0:9] == "1-0:1.8.2":
                    readings["T2"] = float(x[10:19])*1000
            return readings
    except Exception as e:
        sys.stderr.write("An error occurred: %s\n" % e)


def main():
    if 'config' in sys.argv:
        print "graph_title Huidig elektra verbruik in Watt"
        print "graph_args --base 1000 -l 0"
        print "graph_vlabel Watt"
        print "graph_scale  no"
        print "graph_category sensors"
        print "c.label Huidig verbruik"
        print "c.type GAUGE"
        print "c.draw LINE"
        print "c.min 0"

    readings = readserial()
    logdata([readings["huidig"]])
    print "c.value", int(round(readings["huidig"]))

if __name__ == "__main__":
    main()
