#!/usr/bin/python
#
# Reads temperature from 1-wire DS18B20 temperature
# sensors.
#
# Enable 1-Wire in raspi-config advanced menu. 
# 
# Add to rc.local:
# sudo modprobe w1-gpio
# sudo modprobe w1-therm
#
# See https://learn.adafruit.com/adafruits-raspberry-pi-lesson-11-ds18b20-temperature-sensing/ds18b20
#
#
import sys
import os

device1 = '28-0414608a03ff' # binnen
label1 = 'kast temperatuur'

device2 = '28-041460b254ff' # buiten
label2 = 'buiten temperatuur'

def read_temp_raw(device_file):
    f = open(device_file, 'r')
    lines = f.readlines()
    f.close()
    return lines
 
def read_temp(device):
    device_file = '/sys/bus/w1/devices/'+device+'/w1_slave'
    lines = read_temp_raw(device_file)
    while lines[0].strip()[-3:] != 'YES':
        time.sleep(0.2)
        lines = read_temp_raw()
    equals_pos = lines[1].find('t=')
    if equals_pos != -1:
        temp_string = lines[1][equals_pos+2:]
        temp_c = float(temp_string) / 1000.0
        return temp_c

if len(sys.argv) > 1 and (str(sys.argv[1])) == 'config':
    print 'graph_title Temperature'
    print 'graph_args --lower-limit 0 --base 1000'
    print 'graph_vlabel Celcius'
    print 'graph_category sensors'
    print 'graph_info Temperature in degrees celcius'
    print 'graph_period minute'
    print device1 + '.label ' + label1
    print device1 + '.type GAUGE'
    print device1 + '.draw LINE' 
    print device2 + '.label ' + label2
    print device2 + '.type GAUGE'
    print device2 + '.draw LINE' 

print device1 + '.value ' + str(read_temp(device1))
print device2 + '.value ' + str(read_temp(device2))
